spring:
  application:
    name: itsm-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://itsm-db:3306/itsm_db}
    username: ${SPRING_DATASOURCE_USERNAME:itsm_user}
    password: ${SPRING_DATASOURCE_PASSWORD:itsm_password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health" # 필요한 엔드포인트를 노출합니다.
  endpoint:
    health:
      show-details: always # 상세 상태(DB 연결 등)를 항상 표시합니다.